name: Portafolio CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.2

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.3.0
          cache: 'pnpm'

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Validar tipos y Astro Check
        run: pnpm run check

      - name: Intentar Build de Producción
        run: pnpm run build